services:
    OHMedia\FileBundle\Service\FileManager:
        arguments: ["%kernel.project_dir%", "%oh_media_file.upload_dir%"]

    ohmedia_file.file_manager:
        alias: OHMedia\FileBundle\Service\FileManager

    OHMedia\FileBundle\Twig\FileExtension:
        arguments: ["@doctrine.orm.entity_manager", "@ohmedia_file.file_manager"]
        tags:
            - { name: twig.extension }

    ohmedia_file.file_extension:
        alias: OHMedia\FileBundle\Twig\FileExtension

    OHMedia\FileBundle\EventListener\FileSubscriber:
        arguments: ["@ohmedia_file.file_manager"]
        tags:
            - { name: 'doctrine.event_subscriber' }

    OHMedia\FileBundle\Form\Type\FileEntityType:
        arguments: ["@ohmedia_file.file_manager"]
        tags:
            - { name: form.type }

    OHMedia\FileBundle\Repository\FileRepository:
        autowire: true
        tags:
            - { name: doctrine.repository_service }

    ohmedia_file.repository:
        alias: OHMedia\FileBundle\Repository\FileRepository

    OHMedia\FileBundle\Repository\FileFolderRepository:
        autowire: true
        tags:
            - { name: doctrine.repository_service }

    OHMedia\FileBundle\Repository\ImageRepository:
        autowire: true
        tags:
            - { name: doctrine.repository_service }

    OHMedia\FileBundle\Repository\ImageResizeRepository:
        autowire: true
        tags:
            - { name: doctrine.repository_service }

    OHMedia\FileBundle\Cleanup\FileCleaner:
        arguments: ["@ohmedia_file.repository"]
        tags: ["ohmedia_cleanup.cleaner"]
