services:
    OHMedia\FileBundle\Service\FileManager:
        arguments:
            - "@router.default"
            - "%kernel.project_dir%"

    oh_media_file.file_manager:
        alias: OHMedia\FileBundle\Service\FileManager

    OHMedia\FileBundle\Service\FileLifecycle:
        autowire: true

    oh_media_file.file_lifecycle:
        alias: OHMedia\FileBundle\Service\FileLifecycle

    OHMedia\FileBundle\Service\FileFolderSlugger:
        autowire: true

    oh_media_file.file_folder_slugger:
        alias: OHMedia\FileBundle\Service\FileFolderSlugger

    OHMedia\FileBundle\Service\ImageManager:
        autowire: true

    OHMedia\FileBundle\Service\FileListing:
        autowire: true

    OHMedia\FileBundle\Service\FileResponse:
        autowire: true

    OHMedia\FileBundle\Twig\FileExtension:
        arguments:
            - "@oh_media_file.file_manager"
            - "@oh_media_file.file_repository"
            - "%oh_media_file.file_browser.limit_gb%"
        tags: ["twig.extension"]

    OHMedia\FileBundle\Twig\FileScriptExtension:
        autowire: true
        tags: ["twig.extension"]

    OHMedia\FileBundle\Twig\ImageExtension:
        autowire: true
        tags: ["twig.extension"]

    OHMedia\FileBundle\Twig\WysiwygExtension:
        autowire: true
        tags: ["twig.extension", "oh_media_wysiwyg.extension"]

    OHMedia\FileBundle\EventListener\FileFolderPrePersist:
        arguments: ["@oh_media_file.file_folder_slugger"]
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'prePersist'
                entity: 'OHMedia\FileBundle\Entity\FileFolder'

    OHMedia\FileBundle\EventListener\FileFolderPreUpdate:
        arguments: ["@oh_media_file.file_folder_slugger"]
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'OHMedia\FileBundle\Entity\FileFolder'

    OHMedia\FileBundle\EventListener\FilePostPersist:
        arguments: ["@oh_media_file.file_lifecycle"]
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postPersist'
                entity: 'OHMedia\FileBundle\Entity\File'

    OHMedia\FileBundle\EventListener\FilePostRemove:
        arguments: ["@oh_media_file.file_lifecycle"]
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postRemove'
                entity: 'OHMedia\FileBundle\Entity\File'

    OHMedia\FileBundle\EventListener\FilePostUpdate:
        arguments: ["@oh_media_file.file_lifecycle"]
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'postUpdate'
                entity: 'OHMedia\FileBundle\Entity\File'

    OHMedia\FileBundle\EventListener\FilePrePersist:
        arguments: ["@oh_media_file.file_lifecycle"]
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'prePersist'
                entity: 'OHMedia\FileBundle\Entity\File'

    OHMedia\FileBundle\EventListener\FilePreUpdate:
        arguments: ["@oh_media_file.file_lifecycle"]
        tags:
            -
                name: 'doctrine.orm.entity_listener'
                event: 'preUpdate'
                entity: 'OHMedia\FileBundle\Entity\File'

    OHMedia\FileBundle\Form\Type\FileEntityType:
        arguments: ["@oh_media_file.file_manager", "@oh_media_file.file_repository"]
        tags: ["form.type"]

    OHMedia\FileBundle\Repository\FileRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    oh_media_file.file_repository:
        alias: OHMedia\FileBundle\Repository\FileRepository

    OHMedia\FileBundle\Repository\FileFolderRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    OHMedia\FileBundle\Controller\Backend\FileController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\FileBundle\Controller\Backend\FileFolderController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\FileBundle\Controller\FileController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\FileBundle\Security\Voter\FileVoter:
        arguments: ["%oh_media_file.file_browser.enabled%"]
        tags: ["security.voter"]

    OHMedia\FileBundle\Security\Voter\FileFolderVoter:
        arguments: ["%oh_media_file.file_browser.enabled%"]
        tags: ["security.voter"]

    OHMedia\FileBundle\Service\FileNavItemProvider:
        autowire: true
        tags: ["oh_media_backend.nav_item_provider"]
