services:
    OHMedia\FileBundle\Service\FileManager:
        arguments:
            - "@router.default"
            - "%kernel.project_dir%"

    oh_media_file.file_manager:
        alias: OHMedia\FileBundle\Service\FileManager

    OHMedia\FileBundle\Service\ImageManager:
        autowire: true

    OHMedia\FileBundle\Service\FileListing:
        autowire: true

    OHMedia\FileBundle\Service\FileResponse:
        autowire: true

    OHMedia\FileBundle\Twig\FileExtension:
        autowire: true
        tags: ["twig.extension"]

    OHMedia\FileBundle\Twig\ImageExtension:
        autowire: true
        tags: ["twig.extension"]

    OHMedia\FileBundle\Twig\WysiwygExtension:
        autowire: true
        tags: ["twig.extension", "oh_media_wysiwyg.extension"]

    OHMedia\FileBundle\EventListener\FileSubscriber:
        autowire: true
        tags: ["doctrine.event_subscriber"]

    OHMedia\FileBundle\Form\Type\FileEntityType:
        arguments: ["@oh_media_file.file_manager"]
        tags: ["form.type"]

    OHMedia\FileBundle\Repository\FileRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    OHMedia\FileBundle\Repository\FileFolderRepository:
        autowire: true
        tags: ["doctrine.repository_service"]

    OHMedia\FileBundle\Controller\FileController:
        tags: ["container.service_subscriber", "controller.service_arguments"]
        autowire: true

    OHMedia\FileBundle\Security\Voter\FileVoter:
        tags: ["security.voter"]

    OHMedia\FileBundle\Security\Voter\FileFolderVoter:
        tags: ["security.voter"]
