services:
    OHMedia\FileBundle\Service\FileManager:
        arguments: ["@doctrine.orm.entity_manager", "@router.default", "%kernel.project_dir%"]

    oh_media_file.file_manager:
        alias: OHMedia\FileBundle\Service\FileManager

    OHMedia\FileBundle\Twig\FileExtension:
        arguments: ["@oh_media_file.file_manager"]
        tags:
            - { name: twig.extension }

    oh_media_file.file_extension:
        alias: OHMedia\FileBundle\Twig\FileExtension

    OHMedia\FileBundle\EventListener\FileSubscriber:
        arguments: ["@oh_media_file.file_manager"]
        tags:
            - { name: 'doctrine.event_subscriber' }

    OHMedia\FileBundle\Form\Type\FileEntityType:
        arguments: ["@oh_media_file.file_manager"]
        tags:
            - { name: form.type }

    OHMedia\FileBundle\Repository\FileRepository:
        autowire: true
        tags:
            - { name: doctrine.repository_service }

    oh_media_file.file_repository:
        alias: OHMedia\FileBundle\Repository\FileRepository

    OHMedia\FileBundle\Repository\FileFolderRepository:
        autowire: true
        tags:
            - { name: doctrine.repository_service }

    OHMedia\FileBundle\Repository\ImageRepository:
        autowire: true
        tags:
            - { name: doctrine.repository_service }

    oh_media_file.image_repository:
        alias: OHMedia\FileBundle\Repository\ImageRepository

    OHMedia\FileBundle\Repository\ImageResizeRepository:
        autowire: true
        tags:
            - { name: doctrine.repository_service }

    OHMedia\FileBundle\Cleanup\FileCleaner:
        arguments: ["@oh_media_file.file_repository"]
        tags: ["oh_media_cleanup.cleaner"]

    OHMedia\FileBundle\Controller\FileController:
        tags: ["controller.service_arguments"]
        calls:
            - method: setContainer
              arguments: ["@service_container"]
